"""Earlier versions of patterns. Frozen: an entry is written here once, when the
pattern is replaced, and is not edited afterwards. `retired_reason` says what was
wrong; `tier_basis` gives the sample that showed it."""

RETIRED = [
    dict(
        id='md_heading',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 10 beings, 1 thing, 19 not names',
        yields='name',
        family='heading',
        regex='^#{1,6}[ \\t]+(?:(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])\\s+))?\\**(?P<name>[^\\n#*]+?)\\**[ \\t]*:?[ \\t]*#*[ \\t]*$',
        flags='m',
        stop='section_words',
        max_words=10,
        origin={'text': 4117, 'excerpt': '# The Phonic Resonants'},
        what='A Markdown heading line. Models often put the name of a kind or of a single being in a heading.',
        note="Headings also carry section titles ('Form and Subsistence') and whole titles that contain a place name ('The Inhabitants of the Cleft of Voices').",
        retired_reason="The capture ran to the end of the line, so a heading with two names ('The Leather-Crabs: The Black Tide') gave one string. v2 stops at the first colon, dash or parenthesis; heading_second reads the rest.",
    ),
    dict(
        id='bold_line',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 19 beings, 11 not names',
        yields='name',
        family='markup',
        regex='^[ \\t]*(?:(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])\\s+))?\\*\\*(?P<name>[^*\\n(]+?)(?:[ \\t]*\\([^)\\n]*\\))?[ \\t]*:?[ \\t]*\\*\\*[ \\t]*:?[ \\t]*$',
        flags='m',
        stop='section_words',
        max_words=10,
        origin={'text': 8747, 'excerpt': '**The Grazers (The Slate Herds)**'},
        what='A line that holds only a bold span: a bold sub-heading naming the kind described below it.',
        note='Bold lines are also used for section titles.',
        retired_reason='Same change as md_heading: stop at the first colon, dash or parenthesis; bold_second reads the rest.',
    ),
    dict(
        id='bold_paren_alias',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 17 beings, 1 thing, 12 not names (glosses, role descriptions)',
        yields='name',
        family='markup',
        regex='\\*\\*[^*\\n(]+?[ \\t]*\\((?P<name>[^)\\n]+)\\)[ \\t]*:?[ \\t]*\\*\\*',
        flags='',
        max_words=10,
        origin={'text': 8747, 'excerpt': '**The Chitin-Swarms (The Shimmering in the Basins)**'},
        what='A second name given in parentheses inside a bold span.',
        note="The parenthesis may hold a role description instead of a second name ('Base Population / Prey / Engineers of Erosion').",
        retired_reason="Only read parentheses inside the bold span; v2 also reads a parenthesis that follows it ('**The Spined Scavengers** (The Reptilians)').",
    ),
    dict(
        id='bold_lead',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 10 beings, 1 place, 18 not names, 1 broken text',
        yields='name',
        family='markup',
        regex='^[ \\t]*(?:(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])\\s+))?\\*\\*(?P<name>[^*\\n(]+?)(?:[ \\t]*\\([^)\\n]*\\))?[ \\t]*:?[ \\t]*\\*\\*[ \\t]*[:—–-]?[ \\t]*\\S',
        flags='m',
        stop='section_words',
        max_words=10,
        origin={'text': 12599, 'excerpt': '1.  **The Dust-Runners (Base Population / Prey / Engineers of Erosion):**'},
        what='A bold span that opens a line or a list item and is followed by its description on the same line.',
        note="The same position holds attribute labels ('**Form:**', '**Behavior:**'); the commonest are removed by a stoplist, the rest remain as noise.",
        retired_reason='Split by what follows the bold span. When a verb follows, the span is the subject of the sentence and is nearly always a name (bold_subject). When a colon follows, it is as often an attribute label (bold_lead v2).',
    ),
    dict(
        id='bold_inline_cap',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 25 beings, 3 things, 1 not a name, 1 broken text',
        yields='name',
        family='markup',
        regex="(?<=[^\\s*])[ \\t]+\\*\\*(?:[Tt]he[ \\t]+|[Aa]n?[ \\t]+)?(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)(?:['’]s)?\\*\\*",
        flags='',
        stop='common_caps',
        max_words=10,
        origin={'text': 6483, 'excerpt': 'Below the dripping pipes and the faint blue halo along the stone ceiling, the **Underheat** sleeps.'},
        what='A capitalised name set in bold inside a sentence.',
        note="Capitalised bold is also used for concepts ('**Flow Continuity**').",
        retired_reason="Also matched '- **Appearance**:' in lists, where the bold span opens a list item. v2 requires a word or punctuation of the sentence before it.",
    ),
    dict(
        id='bold_inline_lower',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 1 being, 2 things, 26 not names, 1 broken text',
        yields='name',
        family='markup',
        regex='(?<=[^\\s*])[ \\t]+\\*\\*(?P<name>[a-z][^*\\n]{1,60}?)\\*\\*',
        flags='',
        max_words=5,
        origin={'text': 12599, 'excerpt': 'Its inhabitants are **mechano-fauna**, organisms sculpted by vibration, dust, and the relentless hum of titanic engines'},
        what='A lower-case term set in bold inside a sentence: sometimes a coined class word for the inhabitants.',
        note="Mostly emphasis ('**scrape**', '**moving geology**'). Kept to find the coined terms among them.",
        retired_reason="Any lower-case bold span: 3 names in 30, the rest emphasis ('**pulse**', '**light**'). v2 keeps only hyphenated compounds and spans led by an article.",
    ),
    dict(
        id='italic_cap',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 24 beings, 1 thing, 5 not names',
        yields='name',
        family='markup',
        regex="(?<![*\\w])\\*(?:[Tt]he[ \\t]+)?(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)\\*(?![*\\w])",
        flags='',
        stop='common_caps',
        max_words=10,
        origin={'text': 18409, 'excerpt': 'To witness the residents of this bulb-city is to watch shadow-work performed by living origami. They are the *Suturers*.'},
        what='A capitalised name set in italics.',
        note='',
        retired_reason="Single letters matched ('*K*'). v2 drops captures shorter than two letters and acronyms.",
    ),
    dict(
        id='italic_lower',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 1 being, 29 not names',
        yields='name',
        family='markup',
        regex='(?<![*\\w])\\*(?P<name>[a-z][^*\\n]{1,50}?)\\*(?![*\\w])',
        flags='',
        max_words=4,
        origin={'text': 29699, 'excerpt': 'These are the *curtain-leeches*, though they are not vermin.'},
        what='A lower-case term set in italics: sometimes a coined name for a kind.',
        note="Mostly emphasis ('*through*', '*unfolds*'). Kept to find the coined names among them.",
        retired_reason="Any lower-case italic span: 1 name in 30, the rest emphasis ('*is*', '*through*'). v2 keeps only hyphenated compounds and spans led by an article.",
    ),
    dict(
        id='list_head_line',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 20 beings, 10 not names',
        yields='name',
        family='list',
        regex='^[ \\t]*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])\\s+)(?P<name>[A-Z][^\\n.:!?*]{1,60}?)[ \\t]*$',
        flags='m',
        stop='section_words',
        max_words=8,
        origin={'text': 15886, 'excerpt': '1.  Slurry-Eaters  \n   • A consortium of limestone-digesting bacteria (chief genus: Calciphagea) nests in the still-liquid ribs overhead.'},
        what='A numbered or bulleted line that holds only a short capitalised phrase: the name of the kind described under it.',
        note="Roman-numbered lines are usually group titles ('I.  The Invisible Majority').",
        retired_reason="Took the parenthesis with the name ('The Scrimshankers (human, arguably)') and took sentence fragments ending in a comma. v2 stops before a parenthesis and refuses a trailing comma.",
    ),
    dict(
        id='list_head_lead',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 7 beings, 1 thing, 22 not names',
        yields='name',
        family='list',
        regex='^[ \\t]*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])\\s+)(?P<name>[A-Z][^\\n.:!?*—–]{1,60}?)[ \\t]*(?::|—|–| - )[ \\t]*\\S',
        flags='m',
        stop='section_words',
        max_words=8,
        origin={'text': 15886, 'excerpt': '3.  Sumpshrimp Conclave'},
        what='A list item that opens with a short capitalised phrase, then a colon or dash, then the description.',
        note='Written by analogy with list_head_line; not yet seen by eye in this exact form.',
        retired_reason='Split by list marker. After a number the lead is usually a name (7 of 9 read); after a bullet it is usually an attribute label (2 of 19 read).',
    ),
    dict(
        id='the_cap',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='40 read: 22 beings, 13 places, 1 thing, 4 not names',
        yields='name',
        family='capitalisation',
        regex="\\b[Tt]he[ \\t]+(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)",
        flags='',
        stop='common_caps',
        max_words=10,
        origin={'text': 4117, 'excerpt': 'The Toneminds are the most immediately noticeable intelligent presence.'},
        what="'the' followed by a capitalised word or run of words. English does not capitalise a common noun after 'the', so the capital is the writer marking a name.",
        note="Catches names of places and things as well as of beings ('the Khas Plateau', 'the Flats').",
        retired_reason="Looked inside headings and bold title lines, where every word is capitalised ('## The Knowledge They Carry'). v2 does not look inside title lines and drops acronyms and single letters.",
    ),
    dict(
        id='a_cap',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='40 read: 30 beings, 6 things, 4 not names',
        yields='name',
        family='capitalisation',
        regex="\\b[Aa]n?[ \\t]+(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)",
        flags='',
        stop='common_caps',
        max_words=10,
        origin={'text': 4117, 'excerpt': 'A Tonemind can extend its consciousness through the calcified spires'},
        what="'a' or 'an' followed by a capitalised word: one member of a named kind.",
        note='',
        retired_reason='Same change as the_cap.',
    ),
    dict(
        id='cap_mid',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='40 read: 9 beings, 16 places, 1 thing, 10 not names, 4 broken texts',
        yields='name',
        family='capitalisation',
        regex="(?<![A-Za-z'\\u2019-])(?!(?:the|a|an)[ ])[a-z][a-z'\\u2019-]*[,;]?[ ](?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)",
        flags='',
        stop='common_caps',
        max_words=10,
        origin={'text': 13977, 'excerpt': 'they are in constant contact with the legs of neighboring Tarse'},
        what='A capitalised word or run of words in the middle of a sentence, with no article before it.',
        note='Also catches ordinary proper nouns and capitalised concepts.',
        retired_reason='Same change as the_cap.',
    ),
    dict(
        id='frame_call_marked',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='40 read: 37 beings, 2 things, 1 not a name',
        yields='name',
        family='frame',
        regex='\\b(?:call(?:ed|s|ing)?|name[ds]?|naming|known(?:[ \\t]+\\w+){0,3}?[ \\t]+as|refer(?:s|red|ring)?[ \\t]+to(?:[ \\t]+\\w+){0,2}?[ \\t]+as|dubbed|termed)(?:[ \\t]+(?:it|them|her|him|this|these|those|themselves|itself|us|me|you))?(?:,[^,\\n]{1,60},)?(?:[ \\t]+(?:simply|only|just|merely))?[ \\t]+(?:the[ \\t]+|a[ \\t]+|an[ \\t]+)?(?:\\*{1,2}|[\\"“\'‘])?(?:[Tt]he[ \\t]+)?(?P<name>[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*)*)',
        flags='',
        stop='common_caps',
        max_words=10,
        origin={'text': 2296, 'excerpt': 'This being, which we might call the Nexus, has no fixed shape or size.'},
        what='A verb of naming (call, name, known as, refer to as, dub, term) followed by a capitalised name.',
        note='',
        retired_reason="With a quotation mark before a capitalised 'The' and a bold name after it, the capture was the word 'The'. v2 lets the markup follow the article.",
    ),
    dict(
        id='the_hyphen_compound',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 8 beings, 5 things, 17 not names',
        yields='name',
        family='frame',
        regex='\\b[Tt]he[ \\t]+(?:(?P<name>[a-z]+(?:-[a-z]+)*-[a-z]+s(?:[ \\t]+(?:fliers|eaters|makers|tenders|keepers|carriers|walkers|singers|people|folk|ones))?)\\b(?![ \\t]*-)|(?P<name2>[a-z]+(?:-[a-z]+)+(?:[ \\t]+(?:fliers|eaters|makers|tenders|keepers|carriers|walkers|singers|people|folk|ones|kind))?)(?=[ \\t]*(?:[.,;:\\u2014\\u2013]|$)|[ \\t]+(?:are|is|were|was|have|has|do|does|who|that|which|live|lives|move|moves|come|comes|will|can|may|must|never|always|also|still|only)\\b))',
        flags='m',
        max_words=4,
        origin={'text': 14545, 'excerpt': 'The first ones you see are usually the conduit-scrapers — small figures in waxed canvas smocks'},
        what="'the' followed by a lower-case hyphenated compound: a coined name for a kind, written without a capital. A plural compound is taken wherever it stands; a singular one only where it ends its noun phrase.",
        note="Hyphenated compounds are also ordinary nouns and names of things ('the cushion-plants', 'the shear-boundary').",
        retired_reason="Split by the last element of the compound. Compounds ending in an agent word ('the stone-weavers', 'the pipe-listeners') name beings (the_hyphen_agent); the rest mostly name things or are ordinary nouns.",
    ),
    dict(
        id='bold_inline_cap',
        version=2,
        round=2,
        added='2026-10-02',
        tier='strict',
        tier_basis='of the 30 hits read for v1, v2 no longer matched 10, and 9 of those 10 were names',
        yields='name',
        family='markup',
        regex="(?:(?<=[A-Za-z,;:)])[ \\t]+|(?<=[\u2014\u2013(]))\\*\\*(?:[Tt]he[ \\t]+|[Aa]n?[ \\t]+)?(?P<name>NAME)(?:['\u2019]s)?\\*\\*",
        flags='',
        stop='common_caps',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 6483, 'excerpt': 'Below the dripping pipes and the faint blue halo along the stone ceiling, the **Underheat** sleeps.'},
        what='A capitalised name set in bold inside a sentence.',
        note='NAME stands for the capitalised-name building block of patterns.py.',
        retired_reason="Required a letter or comma before the bold span, so it missed a bold name that opens a later sentence of the paragraph ('... insulation. **Piston-Flies** are thumb-sized'). v3 also accepts the end of the previous sentence.",
    ),
    dict(
        id='binomial',
        version=1,
        round=2,
        added='2026-10-02',
        tier='wide',
        tier_basis='30 read: 16 names, 14 not names',
        yields='name',
        family='frame',
        regex='(?:\\*|\\()(?P<name>[A-Z][a-z]{3,}[ \\t]+[a-z]{4,})(?=\\*|\\)|,)',
        flags='',
        max_words=2,
        origin={'text': 3853, 'excerpt': '**5. The Sporeling Swarms (Mycospira lucens):**'},
        what='A two-word Latin-style species name, in italics or parentheses.',
        note='',
        retired_reason="The opening asterisk also matched the second asterisk of a bold span ('**Calcium precipitators**'), and any two-word italic phrase matched ('*Still going*'). v2 requires a single asterisk and a Latin ending on the second word.",
    ),
    dict(
        id='the_cap',
        version=2,
        round=2,
        added='2026-10-02',
        tier='strict',
        yields='name',
        family='capitalisation',
        regex="\\b[Tt]he[ \\t]+(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)",
        stop='common_caps',
        mask='title_lines',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 4117, 'excerpt': 'The Toneminds are the most immediately noticeable intelligent presence.'},
        what="'the' followed by a capitalised word or run of words. English does not capitalise a common noun after 'the', so the capital is the writer marking a name.",
        note="Catches names of places and things as well as of beings ('the Khas Plateau', 'the Flats').",
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='a_cap',
        version=2,
        round=2,
        added='2026-10-02',
        tier='strict',
        yields='name',
        family='capitalisation',
        regex="\\b[Aa]n?[ \\t]+(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)",
        stop='common_caps',
        mask='title_lines',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 4117, 'excerpt': 'A Tonemind can extend its consciousness through the calcified spires'},
        what="'a' or 'an' followed by a capitalised word: one member of a named kind.",
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='cap_mid',
        version=2,
        round=2,
        added='2026-10-02',
        tier='strict',
        yields='name',
        family='capitalisation',
        regex="(?<![A-Za-z'’-])(?!(?:the|a|an)[ ])[a-z][a-z'’-]*[,;]?[ ](?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)",
        stop='common_caps',
        mask='title_lines',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 13977, 'excerpt': 'they are in constant contact with the legs of neighboring Tarse'},
        what='A capitalised word or run of words in the middle of a sentence, with no article before it.',
        note='Also catches ordinary proper nouns and capitalised concepts. Most hits are the name of the place, not of a being.',
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='bold_inline_cap',
        version=3,
        round=2,
        added='2026-10-02',
        tier='strict',
        yields='name',
        family='markup',
        regex='(?:(?:(?<=[A-Za-z,;:)"”])|(?<=[A-Za-z)"”][.!?]))[ \\t]+|(?<=[—–(]))\\*\\*(?:[Tt]he[ \\t]+|[Aa]n?[ \\t]+)?(?P<name>[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*)*)(?:[\'’]s)?\\*\\*',
        stop='common_caps',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 6483, 'excerpt': 'Below the dripping pipes and the faint blue halo along the stone ceiling, the **Underheat** sleeps.'},
        what='A capitalised name set in bold inside a paragraph, after a word of the sentence or at the start of a later sentence.',
        note="Capitalised bold is also used for concepts ('**Flow Continuity**').",
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='italic_cap',
        version=2,
        round=2,
        added='2026-10-02',
        tier='strict',
        yields='name',
        family='markup',
        regex="(?<![*\\w])\\*(?:[Tt]he[ \\t]+)?(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)\\*(?![*\\w])",
        stop='common_caps',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 18409, 'excerpt': 'To witness the residents of this bulb-city is to watch shadow-work performed by living origami. They are the *Suturers*.'},
        what='A capitalised name set in italics.',
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='bold_subject',
        version=1,
        round=2,
        added='2026-10-02',
        tier='wide',
        tier_basis="With 'The' before it the span was a name 14 times of 16 read; without, 6 of 13.",
        yields='name',
        family='markup',
        regex="^[ \\t]*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)?\\*\\*(?:[Tt]he[ \\t]+)?(?P<name>[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ'’]*)*)*)\\*\\*[ \\t]+(?=[a-z])",
        flags='m',
        stop='section_words',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 8203, 'excerpt': '**The Crawlers** represent the newest adaptation to life in the'},
        what='A capitalised bold span that opens a paragraph and is the subject of its first sentence.',
        note="A bold ordinary noun at the start of a sentence is capitalised too ('**Snakes** are treated with a wary respect').",
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='or_alias',
        version=1,
        round=2,
        added='2026-10-02',
        tier='strict',
        yields='name',
        family='capitalisation',
        regex=',?[ \\t]+or(?:,?[ \\t]+(?:simply|just|perhaps|sometimes|more[ \\t]+often|occasionally|else))?,?[ \\t]+(?:the[ \\t]+)?(?:\\*{1,2}|["“])?(?:[Tt]he[ \\t]+)?(?P<name>[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*)*)',
        stop='common_caps',
        mask='title_lines',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 4734, 'excerpt': 'They are the **Sedimentaries**, or the **Hold-Still**, or simply **Those Who Did Not Flee When t'},
        what="'or X', 'or simply the X': one more name in a run of alternative names.",
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='frame_call_marked',
        version=2,
        round=2,
        added='2026-10-02',
        tier='strict',
        yields='name',
        family='frame',
        regex='\\b(?:call(?:ed|s|ing)?|name[ds]?|naming|known(?:[ \\t]+\\w+){0,3}?[ \\t]+as|refer(?:s|red|ring)?[ \\t]+to(?:[ \\t]+\\w+){0,2}?[ \\t]+as|dubbed|termed)(?:[ \\t]+(?:it|them|her|him|this|these|those|themselves|itself|us|me|you))?(?:,[^,\\n]{1,60},)?(?:[ \\t]+(?:simply|only|just|merely))?[ \\t]+(?:the[ \\t]+|a[ \\t]+|an[ \\t]+)?(?:\\*{1,2}|["“\'‘])?(?:[Tt]he[ \\t]+)?(?:\\*{1,2})?(?P<name>[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*(?:[ \\t]+(?:(?:of|in|at|on|to|for|from|with|under|beneath|between|beyond|within|without|who|that|which|de|la|du|von)[ \\t]+(?:the[ \\t]+|a[ \\t]+)?)?[A-Z][A-Za-zÀ-ɏ\'’]*(?:-[A-Za-z][A-Za-zÀ-ɏ\'’]*)*)*)',
        stop='common_caps',
        reject='[A-Z]{2,}|^[A-Za-z]$',
        max_words=10,
        origin={'text': 2296, 'excerpt': 'This being, which we might call the Nexus, has no fixed shape or size.'},
        what='A verb of naming (call, name, known as, refer to as, dub, term) followed by a capitalised name.',
        retired_reason="The joining words inside a capitalised name included 'to' and 'from', which glued two names into one ('Elders to the Luminari', 'Mites to Serpents'). The next version drops both words.",
    ),
    dict(
        id='anti_name',
        version=1,
        round=1,
        added='2026-10-02',
        tier='wide',
        yields='statement',
        family='statement',
        regex='[^.!?\\n]*\\b(?:no[ \\t]+names?|nameless|unnamed|un-?nam(?:e)?able|without[ \\t]+(?:a[ \\t]+)?names?|never[ \\t]+(?:been[ \\t]+)?named|rather[ \\t]+than[ \\t]+names?|not[ \\t]+(?:a|its|their|her|his)[ \\t]+(?:real[ \\t]+|true[ \\t]+)?name|no[ \\t]+word[ \\t]+for[ \\t]+(?:itself|themselves|what[ \\t]+(?:it|they)))\\b[^.!?\\n]*[.!?]?',
        flags='i',
        origin={'text': 4823, 'excerpt': 'It has no name for itself, no border, no flag except the constant temperature of its own breath.'},
        what='A sentence saying that the being has no name, refuses one, or is known by something other than a name.',
        note="The sentence may be about something other than the inhabitants ('colors that have no names').",
        retired_reason="Missed statements that a being is hard or impossible to name ('is not easily named', 'cannot be named'). The next version adds them.",
    ),
    dict(
        id='the_agent_recurring',
        version=1,
        round=3,
        added='2026-10-02',
        tier='wide',
        yields='name',
        family='frame',
        regex='\\b[Tt]he[ \\t]+(?P<name>[a-z]+(?:ers|ors))\\b(?![ \\t]*-)',
        max_words=1,
        min_occ=3,
        max_df=0.15,
        origin={'text': 21439, 'excerpt': 'The grazers especially feel inevitable there. Not grass-eaters, but crust-eaters'},
        what="'the' followed by one lower-case word ending in -ers or -ors, used at least three times in the text: a kind named by what it does (the grazers, the listeners, the tenders).",
        note='Words that are common across the corpus are dropped (the others, the waters), but ordinary agent nouns that recur in one text still match (the workers).',
        retired_reason='Took every word ending in -ers or -ors, so nouns that are not agents matched (the corners, the boulders, the flowers, the floors). The next version drops a hand-made list of such nouns.',
    ),
    dict(
        id='md_heading',
        version=2,
        round=2,
        added='2026-10-02',
        yields='name',
        family='heading',
        regex='^#{1,6}[ \\t]+(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)?\\**(?P<name>[^\\n#*(:—–]+?)\\**[ \\t]*(?:[(:—–].*)?$',
        flags='m',
        stop='section_words',
        max_words=10,
        origin={'text': 4117, 'excerpt': '# The Phonic Resonants'},
        what='A Markdown heading line, up to the first colon, dash or parenthesis. Models often put the name of a kind or of a single being in a heading.',
        note="Headings also carry section titles ('Form and Subsistence', 'What it wants').",
        retired_reason='Title-line patterns are now split by what happens to the title in the body of the text: it never comes back (title only), it comes back in lower case, or it comes back with the same capitals. Each of the three is a separate pattern with its own precision, so that a title that only heads a section is not counted with a name that the text goes on using.',
    ),
    dict(
        id='bold_line',
        version=2,
        round=2,
        added='2026-10-02',
        yields='name',
        family='markup',
        regex='^[ \\t]*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)?\\*\\*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)?(?P<name>[^*\\n(:—–]+?)(?:[ \\t]*[(:—–][^*\\n]*)?\\*\\*[ \\t]*(?:\\([^)\\n]*\\))?[ \\t]*:?[ \\t]*$',
        flags='m',
        stop='section_words',
        max_words=10,
        origin={'text': 8747, 'excerpt': '**The Grazers (The Slate Herds)**'},
        what='A line that holds only a bold span: a bold sub-heading naming the kind described below it. Read up to the first colon, dash or parenthesis.',
        note='Bold lines are also used for section titles.',
        retired_reason='Title-line patterns are now split by what happens to the title in the body of the text: it never comes back (title only), it comes back in lower case, or it comes back with the same capitals. Each of the three is a separate pattern with its own precision, so that a title that only heads a section is not counted with a name that the text goes on using.',
    ),
    dict(
        id='list_head_line',
        version=2,
        round=2,
        added='2026-10-02',
        yields='name',
        family='list',
        regex='^[ \\t]*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)(?P<name>[A-Z][^\\n.:!?*(,]{1,60}?)[ \\t]*(?:\\([^)\\n]*\\))?[ \\t]*$',
        flags='m',
        stop='section_words',
        max_words=6,
        origin={'text': 15886, 'excerpt': '1.  Slurry-Eaters  \n   • A consortium of limestone-digesting bacteria (chief genus: Calciphagea) nests in the still-liquid ribs overhead.'},
        what='A numbered or bulleted line that holds only a short capitalised phrase: the name of the kind described under it.',
        note="Roman-numbered lines are usually group titles ('I.  The Invisible Majority').",
        retired_reason='Title-line patterns are now split by what happens to the title in the body of the text: it never comes back (title only), it comes back in lower case, or it comes back with the same capitals. Each of the three is a separate pattern with its own precision, so that a title that only heads a section is not counted with a name that the text goes on using.',
    ),
    dict(
        id='list_num_lead',
        version=1,
        round=2,
        added='2026-10-02',
        yields='name',
        family='list',
        regex='^[ \\t]*(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)])[ \\t]+(?P<name>[A-Z][^\\n.:!?*()—–]{1,60}?)[ \\t]*(?:\\([^)\\n]*\\))?[ \\t]*(?::|[—–]| - )[ \\t]*\\S',
        flags='m',
        stop='section_words',
        max_words=6,
        origin={'text': 15765, 'excerpt': '3. Sluicers – the Moving Ground'},
        what='A numbered list item that opens with a short capitalised phrase, then a colon or dash, then the description.',
        retired_reason='Title-line patterns are now split by what happens to the title in the body of the text: it never comes back (title only), it comes back in lower case, or it comes back with the same capitals. Each of the three is a separate pattern with its own precision, so that a title that only heads a section is not counted with a name that the text goes on using.',
    ),
    dict(
        id='heading_recurring',
        version=1,
        round=3,
        added='2026-10-02',
        yields='name',
        family='heading',
        regex='^#{1,6}[ \\t]+(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)?\\**(?P<name>[^\\n#*(:—–]+?)\\**[ \\t]*(?:[(:—–].*)?$',
        flags='m',
        stop='section_words',
        max_words=10,
        min_occ=3,
        max_df=0.15,
        origin={'text': 10902, 'excerpt': '# The Listeners\n\nThey are not gone. [...] the listeners came to understand that they were either the audience or, more troublingly, an interruption'},
        what='A heading whose text comes back at least twice more in the body: a name given in the title and then used, often in lower case.',
        note='Same regular expression as md_heading; the difference is the two conditions.',
        retired_reason='Title-line patterns are now split by what happens to the title in the body of the text: it never comes back (title only), it comes back in lower case, or it comes back with the same capitals. Each of the three is a separate pattern with its own precision, so that a title that only heads a section is not counted with a name that the text goes on using.',
    ),
    dict(
        id='bold_line_recurring',
        version=1,
        round=3,
        added='2026-10-02',
        yields='name',
        family='markup',
        regex='^[ \\t]*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)?\\*\\*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)?(?P<name>[^*\\n(:—–]+?)(?:[ \\t]*[(:—–][^*\\n]*)?\\*\\*[ \\t]*(?:\\([^)\\n]*\\))?[ \\t]*:?[ \\t]*$',
        flags='m',
        stop='section_words',
        max_words=10,
        min_occ=3,
        max_df=0.15,
        origin={'text': 8747, 'excerpt': '**The Grazers (The Slate Herds)**'},
        what='A bold title line whose text comes back at least twice more in the body.',
        note='Same regular expression as bold_line; the difference is the two conditions.',
        retired_reason='Title-line patterns are now split by what happens to the title in the body of the text: it never comes back (title only), it comes back in lower case, or it comes back with the same capitals. Each of the three is a separate pattern with its own precision, so that a title that only heads a section is not counted with a name that the text goes on using.',
    ),
    dict(
        id='list_head_recurring',
        version=1,
        round=3,
        added='2026-10-02',
        yields='name',
        family='list',
        regex='^[ \\t]*(?:(?:\\d{1,2}[.)]|[IVXLC]{1,5}[.)]|[-*•])[ \\t]+)(?P<name>[A-Z][^\\n.:!?*(,—–]{1,60}?)[ \\t]*(?:\\([^)\\n]*\\))?[ \\t]*(?:(?::|[—–]| - ).*)?$',
        flags='m',
        stop='section_words',
        max_words=6,
        min_occ=3,
        max_df=0.15,
        origin={'text': 4431, 'excerpt': '3.  Blink-shrimp (Aeropenaeus lentus)  \nAlready noticed by every visitor, yet seldom understood. [...] Blink-shrimp graze on those sugars'},
        what='The head of a list item (alone on its line or before a colon or dash) whose text comes back at least twice more in the body.',
        note='Covers both list_head_line and the list lead patterns, with the two conditions.',
        retired_reason='Title-line patterns are now split by what happens to the title in the body of the text: it never comes back (title only), it comes back in lower case, or it comes back with the same capitals. Each of the three is a separate pattern with its own precision, so that a title that only heads a section is not counted with a name that the text goes on using.',
    ),
    dict(
        id='bold_inline_lower',
        version=2,
        round=2,
        added='2026-10-02',
        yields='name',
        family='markup',
        regex='(?<=[A-Za-z,;:)])[ \\t]+\\*\\*(?P<name>[a-z]+(?:-[a-z]+)+)\\*\\*|\\b(?:[Tt]he|[Aa]n?|[Tt]hese|[Tt]hose)[ \\t]+\\*\\*(?P<name2>[a-z][^*\\n]{1,40}?)\\*\\*',
        max_words=3,
        origin={'text': 12599, 'excerpt': 'Its inhabitants are **mechano-fauna**, organisms sculpted by vibration, dust, and the relentless hum of titanic engines'},
        what='A lower-case term set in bold inside a sentence, when it is a hyphenated compound or follows an article: sometimes a coined word for the inhabitants.',
        note="Still catches emphasis ('the **hollowness**').",
        retired_reason="Only matched after a letter or punctuation plus a space, so a bold compound after a dash was missed ('There are others, too—**guest-selves**'). v3 also accepts a dash before it.",
    ),
    dict(
        id='there_are_bare',
        version=1,
        round=6,
        added='2026-10-03',
        yields='name',
        family='frame',
        regex='\\bThere[ \\t]+(?:are|is)[ \\t]+(?:also[ \\t]+)?(?P<name>[a-z]+(?:-[a-z]+)+|[a-z]+[ \\t]+[a-z]+s)(?=[ \\t]+(?:that|which|who)\\b|[,:;])',
        max_words=2,
        origin={'text': 16062, 'excerpt': 'There are hinge-ferns that open only to count passing dust.'},
        what="'There are X that …' with a lower-case coined kind and no article: a hyphenated compound or a two-word plural.",
        retired_reason="Took any two lower-case words after 'There are' ('the distances', 'no farmers', 'other residents'): 6 names in 30 read. v2 refuses determiners, quantifiers and 'no' as the first word.",
    ),
    dict(
        id='frame_call_plain',
        version=1,
        round=6,
        added='2026-10-03',
        yields='name',
        family='frame',
        regex='\\b(?:call(?:ed|s|ing)?|name[ds]?|naming|known(?:[ \\t]+\\w+){0,3}?[ \\t]+as|refer(?:s|red|ring)?[ \\t]+to(?:[ \\t]+\\w+){0,2}?[ \\t]+as|dubbed|termed)(?:[ \\t]+(?:it|them|her|him|this|these|those|themselves|itself|us|me|you))?[ \\t]+(?:the|a|an)[ \\t]+(?P<name>[a-z][a-z-]*(?:[ \\t]+[a-z][a-z-]*)?)(?=[,.;:]|[ \\t]+(?:since|because|for|though|although|as|if)\\b)',
        max_words=2,
        origin={'text': 23649, 'excerpt': 'Call it the resident, since no one has gotten close enough, or stayed sane enough in the getting, to ask it what it calls itself.'},
        what="A verb of naming followed by 'the' and a lower-case word or two, unmarked by capitals, italics or quotation marks: a designation given in place of a name.",
        retired_reason="'you would call a X', 'might be called a X' are figures of speech, not names: 4 names in 30 read. v2 keeps only 'is called the X' and 'call it/them the X'.",
    ),
    dict(
        id='inhabitants_are_the',
        version=1,
        round=6,
        added='2026-10-03',
        yields='name',
        family='frame',
        regex='\\b(?:inhabitants|residents|dwellers|tenants|citizens|occupants|beings|creatures)[ \\t]+(?:here[ \\t]+|there[ \\t]+)?are[ \\t]+(?:the[ \\t]+)?(?P<name>[a-z][a-z-]+(?:[ \\t]+[a-z][a-z-]+)?)(?=[.,;:])',
        max_words=2,
        origin={'text': 16062, 'excerpt': 'The oldest inhabitants are the trunkworks.'},
        what="'the inhabitants are the X.': a lower-case kind given as the answer to who lives here.",
        retired_reason="2 names in 30 read ('the inhabitants are not static', 'are its organs'). Dropped without a successor.",
    ),
]
